### PR TITLE
I'm an idiot for pressing the button too fast

### PR DESCRIPTION
**Pull request by chuggafan**
title explains it

### CODE REVIEW

**Comment by Spootacular** [comment]
Hold off on it for a bit, I've tested it and it does work but there's one minor issue in the comment file writing method. It's using only LF instead of CRLF for new lines.

Or maybe I just hadn't retested it after switching from \n to environment.newline, it should be fine but something's up with archiving so I can't be extra sure on that. Archiving.cs:line 57 is throwing index out of range exception. Not sure what's up there.

Other than that, it worked for me and doesn't require any sort of conversion.

**Comment by chuggafan** [comment]
hmm, really? kk, use \n to write, idrgaf, also i know about the index out of range exception, no clue the cause

**Comment by Spootacular** [comment]
The old file writing method used the environment new line, so I wanted to be sure it stayed consistent. Should be fine though. On the exception I just realized what's going on. It's trying to archive http://wew.lad from my test sub which doesn't even exist, so it's getting stuck trying to parse a response that doesn't match what's expected. Never had that problem til now because I'd always comment out the archiving calls when testing.

**Comment by chuggafan** [comment]
You're right, it uses CRLF, and i know how, it's writing ALL lines, which it uses enviorment.newline for file.writealllines, which is what we previously used

**Comment by Spootacular** [comment]
Yep, removed that link and it works fine. Newlines are as they're supposed to be too, I was just looking at an old file and hadn't rerun it. So it'll pick up right where it left off and will read/write the existing file fine.

**Comment by chuggafan** [comment]
Hmmm, I'll need to test this out on a seperate file

**Comment by chuggafan** [comment]
By the way, we don't need to save EVERY comment seen, only the most recent one, the reason we have it is to see if we've seen the comment yet or not, nd stop if we have

**Comment by chuggafan** [comment]
KK, i've reveiwed it, it's fine, pulling now and will also change some things because it shouldn't be returning unless we set it to return.... but otherwise it's fine

**Pull request merged**
