### PR TITLE
Linux compat

### PR DESCRIPTION
**Pull request by Spootacular**
A few bugfixes included for config file handling, and the archive count is unborked. Tested with mono 4.4.1 on arch linux, as well as on Windows.

### CODE REVIEW

**Comment by chuggafan** [comment]
I was looking at this, flatfile works aswell as the SQL?

**Comment by chuggafan** [comment]
LOL you commited some stuff... 4 hours from now? gg

**Comment by Spootacular** [comment]
Flat files should still work, the only things that really needed to be changed to work on linux was the slashes in the file paths. Ended up removing them entirely since they were kind of unnecessary. Other than that everything else is just bugfix.

I changed my system time to UTC when I installed linux, Windows is unaware of that so the clock is 5 hours ahead now. Ignore the Delorean in my garage.

**Comment by chuggafan** [comment]
Ahhh, Ok then, works for me

**Comment by chuggafan** [comment]
After pull I found a weird error with XML attributes in elements, fixed by changing it to not an element, it thought that an element started with a " for some reason, no clue why :(

**Comment by Spootacular** [comment]
Your config is probably a bit different than mine, you were using an attribute for the SQLite toggle and I changed it to be an element like all the others because of some exception I can't remember anymore

**Comment by chuggafan** [comment]
Yhea, I was using an attribute because of it taking up less space and attributes being able to be done by number inside of an element ¯\_(ツ)_/¯ if it has a bug

**Pull request merged**
